name: Check Python
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11', '3.12']
    env:
      DEBUG_ACCESS_KEY: ${{ secrets.DEBUG_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgnutls28-dev
          pip install -U pip
          pip install -r .github/pythonchecks.txt
          pyproject-build --wheel --outdir dist .
          find dist -name "*.whl" | xargs pip3 install
      - name: Run tests
        run: |
          flake8 --exclude=*/__init__.py,dist/*,build/* --ignore=E501,W503,SFS301,T003,PT009
          #coverage run --branch -m pytest tests
          mypy miraheze --ignore-missing-imports --disallow-untyped-defs
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install pypa/build
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r .github/pythonchecks.txt
      - name: Build a binary wheel
        run: pyproject-build --wheel --outdir dist .
      - name: Publish to PyPi
        if: github.event_name == 'tag'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_token }}

  notify-irc:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() && github.repository_owner == 'miraheze' && ( github.ref == 'refs/heads/master' || github.event_name == 'pull_request' ) }}
    steps:
      - name: succeeded
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'success'
        with:
          channel: "#miraheze-tech-ops"
          server: "irc.libera.chat"
          nickname: miraheze-github
          message: ${{ github.repository }} - ${{ github.actor }} the build passed.
          sasl_password: ${{ secrets.IRC_MIRAHEZEBOTS }}

      - name: failed
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          channel: "#miraheze-tech-ops"
          server: "irc.libera.chat"
          nickname: miraheze-github
          message: ${{ github.repository }} - ${{ github.actor }} the build has errored.
          sasl_password: ${{ secrets.IRC_MIRAHEZEBOTS }}
